baseURL = 'https://www.tomatoink.com/blog/'
title = 'TomatoInk Blog: Eco-Friendly Ink, Toner, Printing, and Related Topics'
theme = 'tiBlog'
publishDir = 'blog'
uglyURLs = true
summaryLength= 15
disqusShortname = 'https-www-tomatoink-com-blog'

[params]
    name= 'TomatoInk'
    description = 'Visit our blog to get a new perspective on sustainable living, eco-friendly travel, healthy (and delicious) food, and much more.latest on ink, toner, and printing essentials for home and business. Get DIY tips, SMB advice, and more.'
    dateFormat = "Jan 02, 2006"

[taxonomies]
	authors = "authors"
	tags = "tags"

[outputs]
    home = ["HTML", "RSS", "JSON"]
    page = ["HTML"]
    section = ["HTML"]
    taxonomy = ["HTML"]
    term = ["HTML"]

[pagination]
    disableAliases = true
    pagerSize = 9

